# ===================================================================
# Spring Boot configuration for the "heroku" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
  instance:
    hostname: todo-sports-ionic.herokuapp.com
    non-secure-port: 80
    prefer-ip-address: false

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: postgres://xjffhyxcbtqybb:075cfc1aa980dc4099c9e73559e94fd1826d54db54a2ad66cbf14a4929e72c8e@ec2-176-34-215-248.eu-west-1.compute.amazonaws.com:5432/darqm3tf6jnfuv
    username: xjffhyxcbtqybb
    password: 075cfc1aa980dc4099c9e73559e94fd1826d54db54a2ad66cbf14a4929e72c8e
    hikari:
      maximumPoolSize: 8
server:
  port: ${PORT:8080}
